1. What is the name of the feature responsible for generating Regex objects?

Ans-  re.compile() is the feature responsible for generation of Regex objects.

2. Why do raw strings often appear in Regex objects?

Ans- Raw strings are used so that backslashes do not have to be escaped

3. What is the return value of the search() method?

Ans- The search() method returns Match objects

In [5]:
import  re
a="vprasad2312@gmail.com"

match=re.search(r"\.", a)
print(match)

<re.Match object; span=(17, 18), match='.'>


4. From a Match item, how do you get the actual strings that match the pattern?

In [7]:
import  re
a="Ineuron Full stack Data Science Program"

match=re.search("Ineuron", a)
print(match.group())

Ineuron


5. In the regex which created from the r'(\d\d\d)-(\d\d\d-\d\d\d\d)', what does group zero cover? Group 2? Group 1?

In [12]:
import re
phoneNumRegex = re.compile(r'(\d\d\d)-(\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('My number is 879-338-4448.')
print(mo.groups()) 
print(mo.group())  
print(mo.group(1)) 
print(mo.group(2))


('879', '338-4448')
879-338-4448
879
338-4448


6. In standard expression syntax, parentheses and intervals have distinct meanings. How can you tell a regex that you want it to fit real parentheses and periods?

Ans- The \. \( and \) escape characters in the raw string passed to re.compile() will match actual parenthesis characters.

In [23]:
import re
phoneNumRegex = re.compile(r'((\d\d\d))-(\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('My phone number is 879-338-4448.')
print(mo.group())

879-338-4448


7. The findall() method returns a string list or a list of string tuples. What causes it to return one of the two options?

Ans- If the regex pattern has no groups, a list of strings matched is returned. if the regex pattern has groups, a list of tuple of strings is returned.

In [24]:
import re
a= """John has scored 89 marks
Lisa has scored 90 marks
David has scored 70 marks"""

p=re.compile("[0-9]")
print(re.findall(p,a))

['8', '9', '9', '0', '7', '0']


8. In standard expressions, what does the | character mean?

Ans- In Standard Expressions | means OR operator.

9. In regular expressions, what does the ? character stand for?

Ans- In regular Expressions, ? characters represents zero or one match of the preceeding group.

In [25]:
import re
txt= "Vivek Prasad"
x= re.findall("Vi.?k",txt)
print(x)

[]


10.In regular expressions, what is the difference between the + and * characters?

In [26]:
import re
txt= "Vivek Prasad"
x= re.findall("Vi.+k",txt)
print(x)

['Vivek']


In [27]:
import re
txt= "Vivek Prasad"
x= re.findall("Vi.*k",txt)
print(x)

['Vivek']


Ans- In Regular Expressions, * Represents Zero ore more occurances of the preceeding group, whereas + represents one or more occurances of the preceeding group.

11. What is the difference between {4} and {4,5} in regular expression?

Ans- {4} means that its preceeding group should repeat 4 times. where as {4,5} means that its preceeding group should repeat mininum 4 times and maximum 5 times inclusively

In [28]:
import re
haRegex = re.compile(r'(Ha){3}')
mo1 = haRegex.search('HaHaHa')
mo2 = haRegex.search('Ha')
print(mo1.group())
print(mo2)

HaHaHa
None


12. What do you mean by the \d, \w, and \s shorthand character classes signify in regular expressions?

Ans- \w – Matches a word character equivalent to [a-zA-Z0-9_]

\d – Matches digit character equivalent to [0-9]


\s – Matches whitespace character (space, tab, newline, etc.)

13. What do means by \D, \W, and \S shorthand character classes signify in regular expressions?

Ans- \W – Matches any non-alphanumeric character equivalent to [^a-zA-Z0-9_]

\D – Matches any non-digit character, this is equivalent to the set class [^0-9]

\S – Matches any non-whitespace character

14. What is the difference between .*? and .*  

Ans- .* is a Greedy mode, which returns the longest string that meets the condition. Whereas .*? is a non greedy mode which returns the shortest string that meets the condition.

15. What is the syntax for matching both numbers and lowercase letters with a character class?

Ans- The Synatax is Either [a-z0-9]

16. What is the procedure for making a normal expression in regax case insensitive?

Ans- We can pass re.IGNORECASE as a flag to make a noraml expression case insensitive

17. What does the . character normally match? What does it match if re.DOTALL is passed as 2nd argument in re.compile()?

Ans- Dot . character matches everything in input except newline character .. By passing re.DOTALL as a flag to re.compile(), you can make the dot character match all characters, including the newline character.

18. If numReg = re.compile(r'\d+'), what will numRegex.sub('X', '11 drummers, 10 pipers, five rings, 4 hen') return?

In [31]:
import re
numReg = re.compile(r'\d+')
numReg.sub('X', '11 drummers, 10 pipers, five rings, 4 hen')

'X drummers, X pipers, five rings, X hen'

19. What does passing re.VERBOSE as the 2nd argument to re.compile() allow to do?

In [36]:
regex_email = re.compile(r"""
                            ^([a-z0-9_\.-]+)              # local Part like username
                            @                             # single @ sign 
                            ([0-9a-z\.-]+)                # Domain name like google
                            \.                            # single Dot .
                            ([a-z]{2,6})$                 # Top level Domain  like com/in/org
                         """,re.VERBOSE | re.IGNORECASE)



20. How would you write a regex that match a number with comma for every three digits? It must match the given following:

In [37]:
import re
pattern = r'^\d{1,3}(,\d{3})*$'
pagex = re.compile(pattern)
for ele in ['42','1,234', '6,368,745','12,34,567','1234']:
    print('Output:',ele, '->', pagex.search(ele))

Output: 42 -> <re.Match object; span=(0, 2), match='42'>
Output: 1,234 -> <re.Match object; span=(0, 5), match='1,234'>
Output: 6,368,745 -> <re.Match object; span=(0, 9), match='6,368,745'>
Output: 12,34,567 -> None
Output: 1234 -> None


'42','1,234', '6,368,745'but not the following: '12,34,567' (which has only two digits between the commas) '1234' (which lacks commas)

21. How would you write a regex that matches the full name of someone whose last name is Watanabe? You can assume that the first name that comes before it will always be one word that begins with a capital letter. The regex must match the following:

'Haruto Watanabe'
'Alice Watanabe'
'RoboCop Watanabe'

but not the following:

'haruto Watanabe' (where the first name is not capitalized)
'Mr. Watanabe' (where the preceding word has a nonletter character)
'Watanabe' (which has no first name)
'Haruto watanabe' (where Watanabe is not capitalized)

In [38]:
import re
pattern = r'[A-Z]{1}[a-z]*\sWatanabe'
namex = re.compile(pattern)
for name in ['Haruto Watanabe','Alice Watanabe','RoboCop Watanabe','haruto Watanabe','Mr. Watanabe','Watanabe','Haruto watanabe']:
    print('Output: ',name,'->',namex.search(name))

Output:  Haruto Watanabe -> <re.Match object; span=(0, 15), match='Haruto Watanabe'>
Output:  Alice Watanabe -> <re.Match object; span=(0, 14), match='Alice Watanabe'>
Output:  RoboCop Watanabe -> <re.Match object; span=(4, 16), match='Cop Watanabe'>
Output:  haruto Watanabe -> None
Output:  Mr. Watanabe -> None
Output:  Watanabe -> None
Output:  Haruto watanabe -> None


22. How would you write a regex that matches a sentence where the first word is either Alice, Bob,or Carol; the second word is either eats, pets, or throws; the third word is apples, cats, or baseballs; and the sentence ends with a period? This regex should be case-insensitive. It must match the following:
'Alice eats apples.'
'Bob pets cats.'
'Carol throws baseballs.'
'Alice throws Apples.'
'BOB EATS CATS.'

but not the following:

'RoboCop eats apples.'
'ALICE THROWS FOOTBALLS.'
'Carol eats 7 cats.'

In [42]:
import re
pattern = r'(Alice|Bob|Carol)\s(eats|pets|throws)\s(apples|cats|baseballs)\.'
casex = re.compile(pattern,re.IGNORECASE)
for ele in ['Alice eats apples.','Bob pets cats.','Carol throws baseballs.','Alice throws Apples.','BOB EATS CATS.','RoboCop eats apples.'
,'ALICE THROWS FOOTBALLS.','Carol eats 7 cats.']:
    print('Output: ',ele,'->',casex.search(ele))



Output:  Alice eats apples. -> <re.Match object; span=(0, 18), match='Alice eats apples.'>
Output:  Bob pets cats. -> <re.Match object; span=(0, 14), match='Bob pets cats.'>
Output:  Carol throws baseballs. -> <re.Match object; span=(0, 23), match='Carol throws baseballs.'>
Output:  Alice throws Apples. -> <re.Match object; span=(0, 20), match='Alice throws Apples.'>
Output:  BOB EATS CATS. -> <re.Match object; span=(0, 14), match='BOB EATS CATS.'>
Output:  RoboCop eats apples. -> None
Output:  ALICE THROWS FOOTBALLS. -> None
Output:  Carol eats 7 cats. -> None
